### ISSUE TITLE
Brutal incompatibility 

### ISSUE THREAD

**Issue by Arch23-tech** [murphy-slaw/deeper_oceans_refabricated#1]
While using this great mod alongside other great mod called (Wf cave overhaul), causing terrible worldgen deformations:

● large chunks in sea (especially deep oceans) not able to generate or just being blank (holes in the ocean generation. 

● large canyon shaped caves (Wf cave overhaul) spawning on surface of oceans.... making it terrible for exploration.

● also I noticed some minor terrain related issues beneath ocean.

I hope those issues get fixed because dozens and dozens of people using (Wf cave overhaul)

Thank you for this massive port to fabric.. without you we would disappointed about this mod originally abandoned...

Thank you for your efforts 🙏

**Comment by murphy-slaw** [comment]
Yeah, this is incompatible because both mods modify terrain generation in incompatible ways. There is no easy way to resolve this that I know of. Leaving this issue open while I do some research, but it might be unfixable.

**Comment by Arch23-tech** [comment]
Hi there
thank you for your efforts, I've talked with the other side, and he said also the issue is unfixable......
so, you close the issue now.

But plz if you could release an 1.20.1 data pack version of this mod, that will help us a ton
